[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[redirects]]
  from = "/*"
##from = "/addalink"
  to = "/index.html"
  status = 200

#[[redirects]]
#  from = "/*"
#  to = "https://www.facebook.com/rogerfirstnationalipswich"
#  status = 200
#  force = true

